### ISSUE TITLE
Allow inscription to contain standard "spoiler" metadata for potentially NSFW or sensitive content

### ISSUE THREAD

**Issue by rayonx** [ordinals/ord#1447]
- Allow a standard metadata label for inscriber to include to mark as "spoiler" content
- Allow explorer to only show content when user clicks on a reveal button (e.g. "Show Spoiler Content")

**Comment by casey** [comment]
Great idea!

This seems reasonable, but at the moment low priority, since problematic content hasn't been too big of an issue.

One thing I'm worried about is that tastes change, so something NSFW now may not be in the future, or vice versa, and we can't allow changing whether it has the spoiler tag.

Although I do like calling it a "spoiler" tag. Marking something as a spoiler is a common practice in many online venues, and could be used for lots of different things, and is very non judgemental.

One thing that would move this along would be if someone figured out a simple implementation. Right now the front-end loads every kind of content in an iframe, which doesn't have any special tags or style that vary per inscription. This has been a great design, and keeps the front end clean, and delegates all rendering to the back end. I want to keep this design, so I don't want to front end to have to query the database when rendering /inscriptions. If someone can come up with a clean design for that, the protocol level stuff is very simple.
