### ISSUE TITLE
Document config file

### ISSUE THREAD

**Issue by hantuzun** [ordinals/ord#1448]
Ordinals and inscriptions are protocols running on Bitcoin just like HTTP or IPFS are protocols running on transport protocols like TCP/IP. Protocols are content agnostic. The nodes however, could have a say on the content they engage with.

Below are my opinions on blocklist and allowlist functionalities (blacklist, whitelist, i.e. censorship) for inscriptions.

For platforms supporting graphic content, the nodes should be able to censor content. I'd prefer @casey to be able to censor inscriptions he doesn't like on [ordinals.com](https://ordinals.com) as I think this would improve the chances of Inscriptions making a big impact.

It's inevitable for Inscriptions nodes to have censorship ability. Some IPFS nodes [[1](https://blog.cloudflare.com/cloudflare-ipfs-safe-mode/)], and Ethereum RPC providers [[2](https://hackmd.io/@gozzy/tornado-cash-post-censorship#RPC)] and validator nodes [[3](https://twitter.com/0xTuzun/status/1620766418383020032)] censor content today.

The earlier we have censorship ability for inscriptions, the less nodes will need to opt-in to censorship. Because, the earlier we have this functionality, the less controversial content will be inscribed.
-  First, knowing that they can be censored today, there will be less incentives to inscribe controversial content.
- Second, ordinal theory will become less controversial over time, as it will benefit Bitcoin. This will reduce the incentives to inscribe controversial content to hurt the project.

Therefore, I suggest we start designing blocklist and allowlist functionalities.

**Comment by hantuzun** [comment]
I didn't see https://github.com/casey/ord/issues/1447 as I was in the editor. I guess one of them should be closed as a duplicate.

**Comment by casey** [comment]
Great issue! I think all your points are valid. Especially the point that the easier it is to hide inscriptions, the less trolls will bother.

We actually have already added this functionality. On `master` you can pass a YAML config using `--config` to `ord`, which has a `hidden` key that can contain a list of inscription IDs. If an ID is in hidden, it will not be returned from /preview or /content, so there's no way of getting the server to return the content.

We used this to hide a (quite mild) pornographic inscription a few days ago, but we don't have any formal moderation policy.

Since this functionality is already in place, I think the issue here is that it needs to be documented.

**Comment by hantuzun** [comment]
It's great to know that blocklist functionality is already in place! I hope this protocol will never need allowlist.

As we agree, documenting this will be effectual as well. Wording it carefully would save more time in the follow up sentiment and arguments.

**Comment by casey** [comment]
This is documented [here](https://docs.ordinals.com/guides/moderation.html).
