### ISSUE TITLE
Add prettier config/ignore

### ISSUE THREAD

**Issue by whoabuddy** [ordinals/ord#1586]
I was looking to correct some typos in the docs, but I have prettier enabled on save and it suggests more changes than I intended to include in the PR.

I can disable it and restart my editor, but it'd be nice if the behavior were instead defined similar to [rustfmt.toml](https://github.com/casey/ord/blob/master/rustfmt.toml) at the root.

**Option A** - add a prettier config for the docs

- add `.prettierignore` at the root to exclude all folders except docs
- add `.prettierrc.toml` in the docs folder
  - tabWidth = 2
  - useTabs = false
  - singleQuote = false
  - printWidth = 100
- run `prettier --write` to format all markdown in /docs one-time
- encourage future commits to use prettier

**Option B** - add a general ignore statement for prettier

- add `.prettierignore` at the root to exclude all folders

I'm happy to open a PR for either option!

**Comment by casey** [comment]
Let's definitely add `.prettierignore` to the root, to make the dev experience better for people who have preittier-on-save.

In a separate PR, since it might need tweaking, want to add a prettierrc.toml in the docs folder? I've been formatting the docs manually, but having consistent formatting and not having to worry about it would be great. That being said it hasn't been a huge problem, but I'm curious to experiment.

If we want, we can also enable it on CI so the docs stay formatted.
