### ISSUE TITLE
RUST_BACKTRACE=1

### ISSUE THREAD

**Issue by random9brat** [ordinals/ord#1674]
Got my indexing stopped at 300.000 block with this error:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', /root/.cargo/registry/src/github.com-1285ae84e5963aae/redb-0.13.0/src/tree_store/page_store/mmap/unix.rs:14:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I cant even reindex it again with the ./ord --bitcoin-data-dir /mypath/ info

EDIT: wallet creation and receiving address are working properly.

**Comment by kaspar-nl** [comment]
Which version of `ord` did you use? Did you use binary of build yourself?

**Comment by random9brat** [comment]
> Which version of `ord` did you use? Did you use binary or build yourself? 

0.4.2...built it myself because had a 'name - u' problem when I run install.sh

**Comment by random9brat** [comment]
> 

any chance of knowing the possible solution?

**Comment by DanielHook15** [comment]
I have exactly the same situation/problem, but with version 0.5.0. The reason why I built from source code is that no binaries for Raspbian were available. My node is a Raspberry PI 4 with Raspbian 32bit.
 
Is it possible that ord works only on 64bit systems?
If yes, will I have to replace Raspbian by Ubuntu (should work also on a Pi) and reinstall Bitcoin Core and ord?

Please help!

**Comment by bnonni** [comment]
@random9brat that error message isn't enough to diagnose the problem. You need to run the command with RUST_BACKTRACE and paste that output. That said, if you were running `ord index` and got this error, you might try starting the sync over by renaming the index.redb file https://github.com/casey/ord/issues/1780. Since you built from source, you might also want to try pulling the latest and rebuilding to lts version (0.5.0).

**Comment by bnonni** [comment]
@DanielHook15 I think you need a 64 bit OS to do just about anything with Bitcoin. If you look at https://bitcoin.org/en/download you'll see only 64 bit versions. I recall having issues building Bitcoin Core from source when I first setup my rpi bc I accidentally installed a 32 bit Ubuntu distro on it. My guess is that ord also needs a 64 bit OS.

I would download Ubuntu 22.04 and reflash your SD card with it https://ubuntu.com/download/raspberry-pi. Then you can reinstall bitcoin core and ord.

**Comment by DanielHook15** [comment]
Thank you very much for the help! 

I downloaded Bitcoin Core from https://bitcoincore.org/en/download/ and clicked on "ARM Linux". Since "32bit 64bit" is written under "ARM Linux", I assumed that I will get one package that works in both cases. As I realize now, however, I got only a version for 32bit. If one wants 64bit, one needs to click on the tiny "64bit" below "ARM Linux". 
As a consequence, it did not work on my Raspbian 64bit and I switched to Raspbian 32bit, where it worked. 
My node is running without any problems since then. 
Adding ord to the node, however, did not work. Thank you for confirming that this is due to the 32bit OS and for informing me that Bitcoin Core does work with 64bit. 

I will try 64bit for Bitcoin Core and ord next.
