### ISSUE TITLE
Ordinals tracking onchain

### ISSUE THREAD

**Issue by jerryfane** [ordinals/ord#1813]
What's the best way to track ordinals transactions onchain?

**Comment by Psifour** [comment]
Scope is much to large. It is likely an issue with the word choice, but as written the answer would be, "Apply Ordinal Theory to all transactions since the genesis block to build an index of Ordinals." 

This is due to the fact that ALL transactions that have output(s) are Ordinal compatible transactions (including block rewards/fees).

**Comment by stet** [comment]
need a registry
