### ISSUE TITLE
Not enough sats on my utxo

### ISSUE THREAD

**Issue by mdrlucky** [ordinals/ord#1865]
Hello

Usually inscription comes with 10000sats for « postage ». 

But, I have an inscription on my utxo with only an output value of 1500 sats. 
my inscription is on the first output, output 0. 

I dont have enough “postage sats”. 

I can use Sparrow to send my inscription 1 input and 1 output but I don’t have enough sats (so only the 1499) to pay the fees. 

I don’t know how to handle it.

**Comment by gmart7t2** [comment]
You can use ord to send the inscription:

    ord wallet send --fee-rate <sats-per-vb> <address> <inscription-id>

The inscription ID ends with i0. You can see it by running:

    ord wallet inscriptions

The `ord wallet send` command will use a cardinal utxo if it needs to.

You can do the same with sparrow but you really have to be careful because sparrow randomizes the order of the tx inputs and outputs. So I would recommend using ord if you can.
