### ISSUE TITLE
Feature Request: Remove Concept of Inscription Numbers Entirely

### ISSUE THREAD

**Issue by dannydeezy** [ordinals/ord#2063]
As an Ordinal Maxi, the only number I care about is Sat Number. There's no need for "inscription numbers". 
Bug solved!

**Comment by habibitcoin** [comment]
ACK

It's a generally unhelpful abstract, and there are already several less abstract ways to go about age/rarity (sat number, block height, etc)

**Comment by jotapea** [comment]
> Bug solved!

I have been surprised (and disappointed) with the "winning" narrative of not wanting to solve the inscription number bugs, because it seems is just for the sake of collectors ($$$). IS STILL EARLY! Any early adopter should know the risks that come with being early.

ACK with the idea of just getting rid of the prioritization of inscription serial numbers. They could still be "used" in some way, like acting as a redirect to the TXIDiN of the actual (latest) indexed inscription position.

**Comment by yihuang** [comment]
inscription number is more storage efficient for internal indexing then inscription id, and inscription number is in the order of inscription creation, so definitely very important for internal indexing. But if exposing in UI, that's a different issue.

**Comment by casey** [comment]
It looks like those fuckers are here to stay 😂
