### ISSUE TITLE
The bitcoin rpcuser password config is phaseout in repo README.md 

### ISSUE THREAD

**Issue by lcgogo** [ordinals/ord#2091]
All the below configs are useless now:

Alternatively, ord can be supplied with a username and password on the command line:

ord --bitcoin-rpc-user foo --bitcoin-rpc-pass bar server

Using environment variables:

export ORD_BITCOIN_RPC_USER=foo
export ORD_BITCOIN_RPC_PASS=bar
ord server

Or in the config file:

bitcoin_rpc_user: foo
bitcoin_rpc_pass: bar

Only the cookie file method is working for current version 0.5.2 and the cookie file can NOT have newline at the end of file

https://github.com/casey/ord/issues/1614#issuecomment-1426067837

**Comment by proskillowner** [comment]
Yes, I also found this problem.
I tried to use custom username and password, but below doesn't work.
ord --bitcoin-rpc-user foo --bitcoin-rpc-pass bar server

**Comment by raphjaph** [comment]
What happens when you run this?

**Comment by casey** [comment]
I think this is currently working. Please open with a repro if not!

**Comment by wudongyang** [comment]
I got this error: 
error: Failed to connect to Bitcoin Core RPC at `127.0.0.1:8332/`:  JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 35)

Macos Apple M1, 14.3.1
Bitcoin Core version v26.1.0
ord 0.18.1

I am sure the bitcoin-rpc-password and bitcoin-rpc-username are both correct. Because bitcoin-cli works fine. 

What other errors might it be?
