### ISSUE TITLE
Please what will happen to the first cursed ordinal?

### ISSUE THREAD

**Issue by SharinganKazekage** [ordinals/ord#2153]
Hello everyone i hope y'all are good 

Please tell me that the first cursed transaction will be counted normally. I minted lot of them and dont want to restart from 0, im student and the impact of minting those nft are real for me.Please cursed developer make the first transaction count as the newest one.. I hope my messages would signifit  something.. Thank you so much for your works team dev cursed and ordinal

**Comment by BatBushRacks** [comment]
@SharinganKazekage for sure these cursed inscriptions should be supported as valid NFTs... I feel for your situation... a lot of people are in the same boat all because of the fiat decision by a few people... not very decentralized... as you may know talk ongoing in these spots... https://github.com/ordinals/ord/pull/2109 https://github.com/ordinals/ord/issues/2151 https://github.com/ordinals/ord/issues/2045 https://github.com/ordinals/ord/pull/2145 https://github.com/ordinals/ord/pull/2154
