### ISSUE TITLE
Cursed client shows more Inscriptions as Ord 0.6.0? Why?

### ISSUE THREAD

**Issue by ChristianGrieger** [ordinals/ord#2166]
I upgraded the ord client to 0_6_0 as it now supports cursed inscriptions.
After the full index I noticed that the cursed client seems to show more Inscriptions as the new Ord client. Can you tell me why? I was thinking the cursed Inscriptions was added and supported now in the main client?

Example: https://cursedordinals.com/inscription/030585bfe0caad9de831378beabdadd0dd7cdc79c7d536543b03dbed94906fadi0
On main explorer: https://ordinals.com/inscription/030585bfe0caad9de831378beabdadd0dd7cdc79c7d536543b03dbed94906fadi0

**Comment by spencerrichardhenry** [comment]
Ord will always be behind other cursed indexers. This is because ord will only ever index cursed inscriptions as it releases a fix for that cursing method, whereas things like cursedordinals.com will find any potential cursing methods and display them for you to see.

So the ord index is only catching the cases of cursing so far handled by ord. Notably this excludes op-66.

**Comment by raphjaph** [comment]
yes exactly
