### ISSUE TITLE
Add wallet flag that allows reinscribing

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#2391]

**Comment by casey** [comment]
I think this should be implemented as follows:

`ord wallet inscribe` takes an optional `--reinscribe` flag. If `--reinscribe` is passed, re-inscription is allowed, and the wallet fails to inscribe if it would not be a reinscription. The implementation should include tests for both cases, i.e. reinscription succeeding, and reinscription failing because there was no prior inscription.

**Comment by Psifour** [comment]
Which of the two do you think is the correct handling.

If --reinscribe is set, but --satpoint is not:

- Ignore the reinscribe as it has no target
- Reinscribe randomly (lol wut)
- Refuse to inscribe without a define inscription ID or satpoint target

**Comment by casey** [comment]
I think probably either `--reinscribe` should only be allowed with `--satpoint`, since the wallet should not be reinscribing anyways by default.

**Comment by Psifour** [comment]
I personally have `--satpoint` acting as a reinscriptions flag in my local branch. Definitely prefer the idea of a dedicated flag like this as a safeguard.
