### ISSUE TITLE
Ord 0.9.x inscription numbers different than 0.7.x and 0.8.x

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#2569]
Inscriptions [35321413](https://ordinals.com/inscription/adc8d37dbce946cf90c1b6c106b8b8404646a7189bb05cede7e40984bef3af5di0) and [35329860](https://ordinals.com/inscription/a1b05b551557ef7365626e561e788ee965fb53f932cebd9b02ff553a8533b096i0) are indexed by ord 0.9.0 but not by ord 0.7.0 or 0.8.0. As a result, 0.9.0 is assigning numbers that are off by 2 from those assigned by older versions.

Both affected inscriptions are the first inscription in a "pointer" test inscription, where no pointer is specified for the first envelope in the witness (since the default offset of 0 is correct and doesn't need a pointer).

**Comment by gmart7t2** [comment]
I heard that ord 0.4.x assigns the same numbers as ord 0.9.x but don't have an index that old to confirm

**Comment by casey** [comment]
Thanks for reporting this! 0.8.0 do parse the first of these inscriptions, but they encounter an error after parsing them, which causes the correctly parsed initial inscription to be ignored. We'll have to replicate this in 0.9.0, and make any inscriptions parsed after an error cursed.

**Comment by decentralizd** [comment]
/popcorn

I am asking what everyone is thinking, what cool name are you giving it?

Bonus points for telling us how to make extra arbitrary value from said curse.

**Comment by casey** [comment]
GUILT BY ASSOCIATION

https://github.com/ordinals/ord/pull/2570

**Comment by casey** [comment]
If we actually add the curse to transaction page, then rare curses will probably be more valuable 🧐

**Comment by sanjfomojis** [comment]
GUILTY 😂

Apologies for accidentally creating more inscription number madness with one of our tests @casey 

Don’t envy you guys at all with the possibility of crazy edge cases always there

Weren’t sure if we should include a pointer for the initial inscription. 

Is the assumption that the first doesn’t need a pointer as it’s usually a valid inscription correct? 

Or would you include a pointer for the first inscription as well?

**Comment by casey** [comment]
It's actually really helpful! Catching things sooner rather than later is great. And having edge-cases in the chain makes them harder to miss, rather than them just being theoretical and hoping that we handle them right.

You're correct, you shouldn't need a pointer if the first inscription should be made on the first sat of its input.

**Comment by sanjfomojis** [comment]
Haha yeah much better now than after a release, lucky @gmart7t2 found it, we’ll try out your patch today

**Comment by devords** [comment]
This is causing two released versions of ord differ in inscription numbers.

Here is 35360664 on ord.io which is not recognized on ME - https://www.ord.io/35360664

And here is the same number 35360664 on ME that's 35360667 on ord.io - https://magiceden.io/ordinals/item-details/b4561cbcf0395240ef2964b7a54dedc5759a54799f0c639ddf3225dcd4deeb4ci0 

🍿

**Comment by kemargrant** [comment]
this is high nonsense. it is time to get an expert to help with this
![image](https://github.com/ordinals/ord/assets/2120365/f61cea07-c189-421e-b74f-a5e33782db85)

**Comment by gmart7t2** [comment]
> Haha yeah much better now than after a release, lucky @gmart7t2 found it, ...

I didn't find it. Benny brought it to my attention here:

https://discord.com/channels/987504378242007100/1018327878745722901/1165048677325357116

![Screenshot_20231021_051512_Discord](https://github.com/ordinals/ord/assets/49558347/9f55bd84-6599-46eb-9288-6d4fc939941c)

**Comment by gmart7t2** [comment]
> We'll have to replicate this in 0.9.0, and make any inscriptions parsed after an error cursed.

What if 0.9.x assigns the same numbers as 0.4.x, as mentioned here?

![Screenshot_20231021_052410_Discord](https://github.com/ordinals/ord/assets/49558347/fd8180fb-da2c-48a6-8bf6-ce4c53d4ea3f)

Wouldn't that suggest that it's 0.7.x and 0.8.x that are "wrong", and that no fix to 0.9.x is required?

**Comment by crypticmeta** [comment]
> > We'll have to replicate this in 0.9.0, and make any inscriptions parsed after an error cursed.
> 
> What if 0.9.x assigns the same numbers as 0.4.x, as mentioned here?
> 
> ![Screenshot_20231021_052410_Discord](https://user-images.githubusercontent.com/49558347/277096831-fd8180fb-da2c-48a6-8bf6-ce4c53d4ea3f.jpg)
> 
> Wouldn't that suggest that it's 0.7.x and 0.8.x that are "wrong", and that no fix to 0.9.x is required?

I hope this is the case, so that i dont need to reindex. lol

**Comment by casey** [comment]
Looking back in releases, it looks like this behavior was introduced in 0.6.0, on 2023-06-04. I'm inclined to consider this a bug in 0.9.0, since 0.6.0 was released a long time ago, the transactions were created after 0.6.0, and people have begun to rely on the behavior of 0.6.0 and beyond.

**Comment by gmart7t2** [comment]
> Looking back in releases, it looks like this behavior was introduced in 0.6.0, on 2023-06-04. I'm inclined to consider this a bug in 0.9.0, since 0.6.0 was released a long time ago, the transactions were created after 0.6.0, and people have begun to rely on the behavior of 0.6.0 and beyond.

Wasn't 0.6.0 the release that disagrees with every other release about inscription numbers? 0.7.0 came out quickly to fix that mess.

The inscriptions in question were made after 0.9.0 was released, and people have come to rely on its behavior too. When the oldest and the newest releases agree on inscription numbers, why would we decide to revert back to accidentally buggy behavior in 0.6 or different buggy behavior in 0.7 and 0.8?

Either way, it's your call.

**Comment by leonidasord** [comment]
I just did a quick analysis of some different tools. 0.9.0 has been out for 40 days and it seems that adoption has been pretty good but not perfect. Tough call. Either way making it sooner rather than later is preferable for the ecosystem so that we can all get aligned again.

USING 0.9.x or 0.5.x and earlier

Ordinals.com
Ordiscan
Ord.io
UniSat
Ordinals Wallet
Ordinals.market
Best in Slot

USING 0.6.x - 0.8.x

Gamma
Magic Eden

**Comment by sanjfomojis** [comment]
Has anyone else tried to build an index with @casey patch? 

I left it going overnight and it was initially going fairly quickly, but woke up now and it’s barely going quicker than bitcoin blocks. 

Probably 40 blocks in the last hour

Might take a while at this rate. 

![Image 22-10-2023 at 8 41 am](https://github.com/ordinals/ord/assets/118575190/5fdcf795-8c8b-4e53-8cae-e8985401d95f)

**Comment by sanjfomojis** [comment]
I spoke too soon, it’s speeding up again, still slow but much quicker than before

**Comment by BennyTheDev** [comment]
OKX and TRAC also between 0.6 and 0.7. 
You can argue TRAC doesn't matter but OKX does for sure.

> I just did a quick analysis of some different tools. 0.9.0 has been out for 40 days and it seems that adoption has been pretty good but not perfect. Tough call. Either way making it sooner rather than later is preferable for the ecosystem so that we can all get aligned again.
> 
> USING 0.9.x or 0.5.x and earlier
> 
> Ordinals.com Ordiscan Ord.io UniSat Gamma Ordinals Wallet Ordinals.market Best in Slot
> 
> USING 0.6.x - 0.8.x
> 
> Magic Eden

**Comment by leonidasord** [comment]
Do we know what UniSat's BRC-20 indexer (or whatever indexer most of the BRC-20 space uses) goes off? I see UniSat is on 0.9.x for exploring inscriptions but have not confirmed BRC-20 impact.

> OKX and TRAC also between 0.6 and 0.8. You can argue TRAC doesn't matter but OKX does for sure. We also had a reorg at 813210, that might make it harder to determine it right now.
> 
> > I just did a quick analysis of some different tools. 0.9.0 has been out for 40 days and it seems that adoption has been pretty good but not perfect. Tough call. Either way making it sooner rather than later is preferable for the ecosystem so that we can all get aligned again.
> > USING 0.9.x or 0.5.x and earlier
> > Ordinals.com Ordiscan Ord.io UniSat Gamma Ordinals Wallet Ordinals.market Best in Slot
> > USING 0.6.x - 0.8.x
> > Magic Eden

**Comment by BennyTheDev** [comment]
I don't know what version they are using, the impact is obvious and who uses what the most doesn't matter. 

You can create transfers and sell them at marketplace x and create & sell different transfers on marketplace y from the same account also. So there is a double-spend kind of situation now. Haven't tested that yet but the way it works, it should be exploitable.

I didn't see none of the marketplaces/influencers warning anyone in the last 24 hrs publicly about that. At least not in the capacity that is required. There is also not "just" BRC-20 that is affected. Let's not forget that.

So while this is getting sorted by the team, isn't it about time to educate people on that?

> Do we know what UniSat's BRC-20 indexer (or whatever indexer most of the BRC-20 space uses) goes off? I see UniSat is on 0.9.x for exploring inscriptions but have not confirmed BRC-20 impact.
> 
> > OKX and TRAC also between 0.6 and 0.8. You can argue TRAC doesn't matter but OKX does for sure. We also had a reorg at 813210, that might make it harder to determine it right now.
> > > I just did a quick analysis of some different tools. 0.9.0 has been out for 40 days and it seems that adoption has been pretty good but not perfect. Tough call. Either way making it sooner rather than later is preferable for the ecosystem so that we can all get aligned again.
> > > USING 0.9.x or 0.5.x and earlier
> > > Ordinals.com Ordiscan Ord.io UniSat Gamma Ordinals Wallet Ordinals.market Best in Slot
> > > USING 0.6.x - 0.8.x
> > > Magic Eden

**Comment by jiedo** [comment]
UniSat uses its own implementation of the ordinals parser instead of ord, but remains consistent with the earlier ord(<=0.5) behavior in parsing.

**Comment by wanyvic** [comment]
OKX's BRC20 parser is based on Ord 0.8.1. We can upgrade to 0.9.0 if there is a consensus in the community.

**Comment by devords** [comment]
I am not sure if the community consensus matters much here. If the protocol team decides that these new _Guilt-by-association_ inscriptions should be treated as cursed in 0.9.x (and versions prior to 0.6.x), it can have significant impact on BRC-20 marketplaces that treated those inscriptions as blessed.

**Comment by leonidasord** [comment]
FWIW my recommendation on next steps here are for Casey or Raph to come out with a clear statement on twitter that 0.9.0 is the source of truth and that people should upgrade. I believe this would bring us to consensus very quickest and have the least impact on the ecosystem.

My logic on why 0.9.0:

-From the analysis I shared on different tools above and subjectively from conversations I've had with different builders, I believe 0.9.0 is likely how the consensus would play out if Casey/Raph said nothing. I understand why Casey's gut reaction was to assume that "people have begun to rely on the behavior of [0.6.x-0.8.x]" however I believe it is a minority relying on 0.6.x-0.8.x now. The majority of tools seem to be on <0.6.x or 0.9.x although there are some large outliers (OKX, ME) both who have expressed they are open to upgrading if that is the direction things go in. (tweets like this are the general sentiment I am subjectively seeing https://x.com/unisat_wallet/status/1716008430870339964?s=20) 

-Given <0.6.0 included these inscriptions and the most reasonable interpretation would be that 0.6.0 introduced a "bug" where they weren't indexed and on top of that the bug was fixed in 0.9.0 and the first instance of the bug occurred 37 days into the 0.9.0 era it feels logical to me to keep 0.9.0 as the source of truth.

**Comment by cbspears** [comment]
> FWIW my recommendation on next steps here are for Casey or Raph to come out with a clear statement on twitter that 0.9.0 is the source of truth and that people should upgrade. I believe this would bring us to consensus very quickest and have the least impact on the ecosystem.

If this is about how to come to consensus on BRC-20 balance state, I think this is probably better addressed by the Layer 1 Foundation coordinating which ord version indexers should use, rather than it being addressed at the ord reference client level. 

The goal of the reference client should be to as accurately as possible reflect the state of recognized Inscriptions, rather than deal with reconciling BRC-20 state mismatch.

There has only been one statement from Domo on the subject on the L1 Foundation forums so far.
https://l1f.discourse.group/t/brc-20-cursed-inscription-content/37/7

**Comment by casey** [comment]
@leonidasord I think that's reasonable. BRC-20 is fragile, but I think it's still reasonable to try to avoid disruption where possible.

I posted on twitter: https://twitter.com/rodarmor/status/1716284984800297380

TL;DR We suggest upgrading to ord 0.9.0 and use it as the source of truth going forward.

**Comment by leonidasord** [comment]
I think this was the right call. Hopefully a decent soft landing. Thanks for coming out with a decisive response.

> @leonidasord I think that's reasonable. BRC-20 is fragile, but I think it's still reasonable to try to avoid disruption where possible.
> 
> I posted on twitter: https://twitter.com/rodarmor/status/1716284984800297380
> 
> TL;DR We suggest upgrading to ord 0.9.0 and use it as the source of truth going forward.
