### ISSUE TITLE
Error inscribing on testnet

### ISSUE THREAD

**Issue by dranastos** [ordinals/ord#2579]
When trying to inscribe on testnet using

ord -t wallet inscribe --fee-rate "1"

i get:
thread 'main' panicked at src/subcommand/wallet/inscribe.rs:150:27:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

when i add a filename at the end  to use to inscribve i get

ord -t wallet inscribe --fee-rate "1" file.txt
error: unexpected argument 'file.txt' found

Usage: ord wallet inscribe [OPTIONS] --fee-rate <FEE_RATE>

Can anyone tell me why neither of these work?

**Comment by casey** [comment]
Thank you for the report! `ord wallet inscribe` can now inscribe from a single file, or from a YAML batch, so a single file is now passed with `--file FILE` and a batch is specified with `--batch BATCHFILE`. Try adding `--file` in front of `file.txt`.

We neglected to make one of `--file` and `--batch` required, which is why you got that confusing error. I opened #2581, which will improve the error message.
