### ISSUE TITLE
RPC errors on master

### ISSUE THREAD

**Issue by grdddj** [ordinals/ord#3049]
I am getting consistent errors with the latest `master` build when trying to do any wallet blockchain action - e.g. `ord wallet balance`

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `404`,
 right: `200`', src/wallet.rs:74:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Assert in question is `assert_eq!(response.status(), StatusCode::OK);` and it seems to be related with the latest PR - https://github.com/ordinals/ord/pull/2929

NOTE: release `0.15.0` is acting fine, even on 4b95ff65, one commit before the abovementioned 08b63805

**Comment by raphjaph** [comment]
We made some big changes to the wallet and server, which we will communicate in our next release. The TLDR is that the wallet now talks to the server via JSON RPC so you will have to run it with `--enable-json-api`. For that reason #3047 now enables the JSON API by default and thus deprecates `--enable-json-api`. So in order to run wallet commands on the current master branch you will have to run the server with `ord server` and after it's started up you can run `ord wallet balance`.
