### ISSUE TITLE
error: error sending request for url (http://127.0.0.1/blockcount): (os error 10061)

### ISSUE THREAD

**Issue by aqfaridi** [ordinals/ord#3411]
E:\ord-0.16.0>ord --cookie-file="E:\data\.cookie" --bitcoin-data-dir="E:\data" wallet balance
error: error sending request for url (http://127.0.0.1/blockcount): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by sherpya** [comment]
you need to start server first with `ord server --http-port 8080` then use `--server-url http://localhost:8080` in the wallet balance command

**Comment by sherpya** [comment]
> E:\ord-0.16.0>ord --cookie-file="E:\data.cookie" --bitcoin-data-dir="E:\data" --server-url http://0.0.0.0:8080 wallet balance
> 
> error: unexpected argument '--server-url' found

you are right, there is the option server_url in the yaml config file I thought a similar (but with dash) option would be in the command line, so you need to find where on windows `ord.yaml` is located (you need to create a new one) and put in:
`server_url: http://localhost:8080`

**Comment by sherpya** [comment]
ok I found it you need to use use the option after `wallet`, e.g.:
`ord wallet --server-url http://127.0.0.1:8080 balance`

**Comment by abdelhamidelkhouider** [comment]
hi guys what about this one ord wallet balance
error: error sending request for url (http://127.0.0.1/blockcount): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
because: No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by abdelhamidelkhouider** [comment]
@bingryan

**Comment by raphjaph** [comment]
Seems like a firewall issue or you are not running `ord server`
