### ISSUE TITLE
Why is Rune 0 (UNCOMMON•GOODS) etching block is 1 and not 0?

### ISSUE THREAD

**Issue by devords** [ordinals/ord#3485]
Considering Bitcoin blocks start at 0, it was surprising to see UNCOMMON•GOODS start at 1. Wondering if there's any specific reasons for this.

cc @gmart7t2

**Comment by casey** [comment]
Because rune ID `0:0` is used to mean the rune currently being etched in a mint transaction. It could be `0:1`, but there is no corresponding transaction, since block 0 has only one transaction, so I went with `1:0`. It doesn't really matter if there's a corresponding transaction, but I was thinking that perhaps some code somewhere would try to look up etching transactions by rune ID, and it would be nice if the transaction for the genesis rune existed.

**Comment by devords** [comment]
Thanks for explaining @casey!
