### ISSUE TITLE
Is it meant to be possible to etch without an inscription, or even a valid "ord" envelope?

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3494]
I see several etchings on testnet which don't have associated inscriptions. For example:

https://testnet.ordinals.com/rune/ABANG%E2%80%A2ABANG%E2%80%A2ABANG

Instead of the usual:

    FALSE
    IF
    "ord"
    RUNE_TAG <rune_id>
    ...
    ENDIF
envelope, it just has the following:

    FALSE
    IF
    <rune_id>
    ENDIF
Is that meant to be a valid etching? It doesn't have the "ord" magic string, but because the commitment pushes the rune_id it is accepted.

**Comment by casey** [comment]
Yup, that's definitely allowed. The rune updater looks through all input witness instructions for a valid commitment, so it doesn't need to be in an envelope or inscription.

And the cheapest way include a commitment is `PUSHDATA <rune_commitment> OP_DROP`, since it saves two instructions over `FALSE IF <rune_commitment> ENDIF`.
