### ISSUE TITLE
error: wallet failed to synchronize with `ord server` after 20 attempts

### ISSUE THREAD

**Issue by jwrookie** [ordinals/ord#3564]
Executing `ord wallet receive`, I get the error `error: wallet failed to synchronize with `ord server` after 20 attempts`

os: ubuntu 20.04
ord version：ord 0.18.1
how to run ord:  nohup ord server &
bitcoin-cli -getinfo: 
<img width="434" alt="image" src="https://github.com/ordinals/ord/assets/41732283/1df3bcac-a6fa-4936-9356-224563db70a3">

**Comment by codecube47** [comment]
Similar issue happen to me, because I created a wallet before bitcoin core sync properly on **testnet**.

Below are the steps i did to fix it:

1. stop syncing
2. remove the wallet that you created before the sync happened ( check you have money on it)
3. start bitcoin core sync
4. do ord indexing
5. if all sync and index then create new wallet 

then all good my side do it only **testnet**

**Comment by jwrookie** [comment]
I have been synchronizing the mainnet data. I suspect that my ord is not fully synchronized, so I have this problem. I am still waiting for the synchronization to be completed.

**Comment by raphjaph** [comment]
Yes, `ord` has to be fully synced. You can also add `ord wallet --nosync balance`

**Comment by waqarilyas** [comment]
> Similar issue happened to me, because I created a wallet before the bitcoin core sync properly on **testnet**.
> 
> Below are the steps I did to fix it:
> 
> 1. stop syncing
> 2. remove the wallet that you created before the sync happened ( check you have money on it)
> 3. start bitcoin core sync
> 4. do ord indexing
> 5. if all sync and index then create new wallet
> 
> then all good my side do it only **testnet**

Can you list the commands as well for this?
