### ISSUE TITLE
Add rune name to decode command

### ISSUE THREAD

**Issue by ygtdmn** [ordinals/ord#3576]
Currently, `ord decode --txid <txhash>` command returns this:

```{
  "inscriptions": [],
  "runestone": {
    "Runestone": {
      "edicts": [],
      "etching": null,
      "mint": "189685:18",
      "pointer": null
    }
  }
}
```

Mint param should also give rune name.

**Comment by raphjaph** [comment]
yes, that would be good to add. Great first issue ;)

**Comment by ldiego08** [comment]
> Currently, `ord decode --txid <txhash>` command returns this:
> 
> ```
>   "inscriptions": [],
>   "runestone": {
>     "Runestone": {
>       "edicts": [],
>       "etching": null,
>       "mint": "189685:18",
>       "pointer": null
>     }
>   }
> }
> ```
> 
> Mint param should also give rune name.

@raphjaph does this mean that the `mint` prop should not only contain the `RuneId` but also `SpacedRune`? Just confirming before giving this a go. Something like:

```
"mint": ["189685:18", "MY•RUNE"]
```

**Comment by raphjaph** [comment]
Just thinking about this again and I think we should not add it. The `ord list` command runs stateless, meaning you don't need a synced index, only a Bitcoin Core node. We just parse out exactly the information that is contained in a tx, we don't apply state to it. Since only the RuneId is in a mint transaction, getting the rune name would mean making a request to the database.
