### ISSUE TITLE
Why `range` always return 0 when I try to index inscriptions

### ISSUE THREAD

**Issue by chenzongxiong** [ordinals/ord#3595]
Command
```
: RUST_LOG=info ./target/debug/ord --bitcoin-rpc-user xxxxxx --bitcoin-rpc-pass xxxxxx  --bitcoin-data-dir "path-to-bitcoin-dir" --first-inscription-height 779832 index update # start from ordi deployment block
```

https://github.com/ordinals/ord/blob/3d969a600f88a5890504bd11d7e166c4de726348/src/index.rs#L2164

`range` always returns 0 and no inscription found. 

Ideally, `ordi` should be indexed at this block

**Comment by cryptoni9n** [comment]
Hi chenzongxiong - I believe this is because you need to have created your ord index with the `--index-sats` flag.  I believe the satpoint_to_sequence_number requires it.  

`ord --bitcoin-rpc-user xxxxxx --bitcoin-rpc-pass xxxxxx  --bitcoin-data-dir "path-to-bitcoin-dir" --first-inscription-height 779832 --index-sats index update`

If you need help creating the new index, please reach out to the #tech-support channel on our official Discord server, [The Ordicord ](https://discord.com/invite/ordinals)
