### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by dreamertodo** [ordinals/ord#3697]
Hello, there is an issue with the display of the RUNE "RICKROLL•AKA•RICK•ASTLEY" video on ordinals.com, as well as an error with the SUPPLY display and ord.exe. How can we address these issues?

https://ordinals.com/rune/RICKROLL%E2%80%A2AKA%E2%80%A2RICK%E2%80%A2ASTLEY

video : 
https://github.com/ordinals/ord/assets/136961839/541e259e-d497-4a78-9cf3-c84373af4571

**Comment by cryptoni9n** [comment]
Hi dreamer, the best way to address issues like these is on one of the test chains before inscribing to mainnet.

Did you test this etch in regtest, signet or testnet? Did you see different results there?

**Comment by dreamertodo** [comment]
Yes, I understand the need for testing, but honestly, before this, I didn't know how to properly use testnet. I wasn't even very proficient in HTML coding. So, I utilized a service called "Recursive Ordinals Builder" (https://www.recursivebuilder.io/) to test. The same code worked well for playing videos on this website. However, after inscribing it, I found that the video couldn't be played correctly. Immediately, I modified the code and confirmed its functionality using signet. Then, I inscribed the new HTML in a parent-child manner on the RUNE: "RICKROLL•AKA•RICK•ASTLEY".

The reason I'm seeking assistance is because during the launch time of this runes, I noticed slight changes in the layout of the ordinals.com website. The purpose of these changes is to provide users with a better experience when viewing data. So, I'm requesting help to ensure that users can correctly view the video and enjoy the original "RICKROLL" meme, aiming for a better user experience.

So I came here hoping to seek help. Thank you for patiently listening.

**Comment by cryptoni9n** [comment]
There are a few issues being presented here:

1. a display issue on the rune page - video only plays when the rune page is browsed to via the back button and not by default

The child inscription 70336141 of the parent 70290087 seems to work properly.  I don't understand why a parent was used instead of simply inscribing the child and using that as the image for the rune.  The child inscription is working well in my browser, where the parent inscription doesn't work well at all and requires the browsing with the back button (and that only seems to work in Chrome). There must be some difference in their encoding even though they have the same content types.

2. the supply on the rune page not matching the supply in the .yaml

this is talked a bit about in #3630.  The supply that shows on the rune page is somewhat misleading, as it reports the total available supply, meaning the total that has been created by premine and mint.  The supply in the yaml refers to the total max supply after all possible mints have been exhausted.  So your rune page shows 39323.1 🎤for the supply right now because that is how much that exists currently. 39320 premined, (the equivalent to 393,200 mints, + 3.1 (for the 31 mints).  After a total of 1,572,800 mints, it will mint out and then there would be a total of 196,600, because premine + (supply * amount) = 39,320 + (1,572,800*.1) = 39,320 + 157,280 = 196,600.  

3. the rune amount field in the yaml matches the rune page, but not the batch command output from the terminal window

The amount set in the yaml is the defacto configuration that dictates how the rune will be etched.  The terminal output information is clearly different here, and I'm not exactly sure why.  I feel like it could be an issue/bug with the way the amount is displayed or by design due to some decision I'm not aware of.  In any case, you would always first want to go by what is in the yaml, because that is what is etched and appears on the rune page.

**Comment by dreamertodo** [comment]
Thank you for your detailed response. Your insights into the issues presented are greatly appreciated. I'll take your guidance and work through each problem methodically to ensure they are addressed effectively. Your assistance is invaluable in resolving these matters.
