### ISSUE TITLE
How to determine if a transaction is a Runes transaction

### ISSUE THREAD

**Issue by Sayplaydiv** [ordinals/ord#3738]
May I ask how to determine if a transaction is a Runes transaction? Is there a corresponding index ledger? The ord node did not find the corresponding interface

**Comment by cryptoni9n** [comment]
Hi Sayplaydiv,

There are a few ways depending on what interface you are utilizing to view the tx.  On [mempool.space](https://mempool.space/), for example, [this is the tx](https://mempool.space/tx/fa5f747dd1eca8e0ba246d53a39b1c7eb0cc1e340c3cc78258d39bb8fe9ac9ed) for the etching of the SATOSHI.NAKAMOTO rune.  When you view [the tx on ordinals.com](https://ordinals.com/tx/fa5f747dd1eca8e0ba246d53a39b1c7eb0cc1e340c3cc78258d39bb8fe9ac9ed), you can see that it is a rune etching tx because it shows the etching with the inscription genesis for inscription 70279601.

ord has the ability to index runes by using the `ord --index-runes` flag.

In the future, I'd encourage you to post questions like these to [the Ordicord](https://discord.com/invite/ordinals) instead of GitHub.  Mods and trusted tech help are usually much more available to answer these sorts of inquiries much quicker than you'll find here.
