### ISSUE TITLE
why is this inscription incorrect?

### ISSUE THREAD

**Issue by sharphill2022** [ordinals/ord#3798]
I found such an inscription on testnet3, but I can't find it on ordinals.com. Can you tell me why this inscription is wrong? Thank you.

OP_PUSHBYTES_33 02d1c2aebced475b0c672beb0336baa775a44141263ee82051b5e57ad0f2248240
OP_CHECKSIG
OP_0
OP_IF
OP_PUSHBYTES_3 6f7264
OP_PUSHBYTES_1 01
OP_PUSHBYTES_24 746578742f706c61696e3b636861727365743d7574662d38
OP_0
OP_PUSHBYTES_56 7b226f70223a227472616e73666572222c2270223a226272632d3230222c227469636b223a226d6f6e61222c22616d74223a22313030227d
OP_ENDIF

https://mempool.space/testnet/tx/c769750df54ee38fe2bae876dbf1632c779c3af780958a19cee1ca0497c78e80#vin=0

**Comment by cryptoni9n** [comment]
Hi sharphill2022 - I'm not sure I completely understand your question, but here's what I would say.

1) that tx won't be on ordinals.com because https://ordinals.com is mainnet and this tx is from testnet
2) normally, the tx would be found on https://testnet.ordinals.com but that site is down for the time being.
3) [here](https://with18testnet.ordstuff.info/output/c769750df54ee38fe2bae876dbf1632c779c3af780958a19cee1ca0497c78e80:0) is the tx on @gmart7t2's testnet instance
4) if you compare against [another inscription](https://with18testnet.ordstuff.info/inscription/6e9ba2127c8d93ba7c684494ed89f2fba80698b86c843798bbf60b815c4555aci0), you can see [it has many PUSHDATA lines](https://mempool.space/testnet/tx/6e9ba2127c8d93ba7c684494ed89f2fba80698b86c843798bbf60b815c4555ac:#vin=0).  Maybe that is what you mean when you're asking why it's wrong?

**Comment by sharphill2022** [comment]
Thanks for your reply, @cryptoni9n .
I have checked on testnet.ordinals.com and can't find this inscription. 
My question is why this inscription can't be identied as an inscription. what is the reason?

**Comment by cryptoni9n** [comment]
> Thanks for your reply, @cryptoni9n . I have checked on testnet.ordinals.com and can't find this inscription. My question is why this inscription can't be identied as an inscription. what is the reason?



> Thanks for your reply, @cryptoni9n . I have checked on testnet.ordinals.com and can't find this inscription. My question is why this inscription can't be identied as an inscription. what is the reason?

The tx doesn't have a valid [inscription](https://docs.ordinals.com/inscriptions.html) envelope.  

> Envelopes consist of an `OP_FALSE` `OP_IF … OP_ENDIF` wrapping any number of data pushes.

It looks like your tx is missing the `OP_FALSE` line

**Comment by sharphill2022** [comment]
OP_0 is the same as OP_FALSE, so that's not the real reason.

**Comment by cryptoni9n** [comment]
> OP_0 is the same as OP_FALSE, so that's not the real reason.

You're right - thanks for the correction, I was unaware.  I'm not sure why then it isn't being recognized as a valid inscription.  Maybe you could provide some details on how it was created?  What type of inscription is it supposed to be?

**Comment by sharphill2022** [comment]
All these data are on testnet. I also was confused with this case and looking for the reason here...

**Comment by sharphill2022** [comment]
not me inscribed it. I just saw it and don't know why ordinals indexer can't recognize it as a correct inscription. from the aspect of ordinals protocol, this looks like a good inscription.

**Comment by cryptoni9n** [comment]
> not me inscribed it. I just saw it and don't know why ordinals indexer can't recognize it as a correct inscription. from the aspect of ordinals protocol, this looks like a good inscription.

ok, thanks for the additional information.  It appears to be an attempted BRC-20 inscription.  I compared it to 5 other valid BRC-20 inscription P2TR tapscripts (all different tickers) and the only difference that sticks out as unique to the bad script is that it uses an OP_PUSHBYTES_33 for the public key while all other valid scripts used OP_PUSHBYTES_32.  This is my best guess at what the issue seems to be.  What do you think?

**Comment by sharphill2022** [comment]
i agree with what you found.  But from the ordinals protocol, it only processes the data in the envelope. So do you think ordinals protocol also processes the script out of the envelope?

**Comment by cryptoni9n** [comment]
> i agree with what you found. But from the ordinals protocol, it only processes the data in the envelope. So do you think ordinals protocol also processes the script out of the envelope?

Not necessarily, but if the public key was malformed, perhaps it could come out like this?  In any case, it seems that we're chasing a mystery here and without further details on how it was inscribed, it's just a guessing game as to what went wrong.

**Comment by sharphill2022** [comment]
Yes. This is just an example on testnet, no such example on mainnet. It seems to be a better choice to ignore it.
