### ISSUE TITLE
Restarting takes too long

### ISSUE THREAD

**Issue by heipacker** [ordinals/ord#3819]
Restarting takes too long

**Comment by cryptoni9n** [comment]
> Restarting takes too long



> Restarting takes too long

Hi heipacker - restarting what takes too long?  Please provide much more detail about what you're doing, how you're doing it, and the problem you're facing if you'd like any meaningful help.

**Comment by heipacker** [comment]
My node oomed, and I restarted it, and it took 5 hours for the http interface to be available.

**Comment by cryptoni9n** [comment]
> My node oomed, and I restarted it, and it took 5 hours for the http interface to be available.

If this is an ord node that you're referring to, the only reason I can think of for any delay in start time is if your index became corrupted and needed to repair, which often times takes many hours.  

You can avoid index corruption when shutting down by always ensuring that you stop ord gracefully.  If you just restarted your machine without gracefully shutting down ord, then this is what likely caused the corruption.  You need to make sure that you manually stop ord by using ctrl-C once, not twice.  You should see the message `Shutting down gracefully. Press <CTRL-C> again to shutdown immediately.`  The trick is to never hit ctrl-c again once you see this message because it will corrupt the index, which will add a lot of time to start up.

This is all I can offer you based on the little information you've provided.  In the future, please bring issues like this to the tech-support channel in [the Ordicord](https://discord.com/invite/ordinals).  It is a much more suitable place for troubleshooting.

**Comment by gus4rs** [comment]
You are always closing "as completed" every issue reported about shutdown, but this doesn't solve them. There is some glaring bottleneck in the underlying database making the graceful shutdown incredibly long. It is quite easy to reproduce 100% of the time:

1) Index with 
```
ord  --index-addresses --index-transactions --index-sats --index-runes  
```

2) CTRL+C 

3) Wait at least 20 minutes in a top notch server with 64GB RAM and NVMe SSD disks for the shutdown to complete, while the log prints "Flushing XXX"

**Comment by gus4rs** [comment]
> Stopping an ord index with sats doesn't take me very long 

How long does it take for you? What are your indexing options?

**Comment by cryptoni9n** [comment]
On average, it takes me 20-30 seconds to stop ord.exe gracefully, regardless of if the index is with or without sats.

**Comment by gus4rs** [comment]
Not indexing transactions doesn't make a visible difference; stopping the process gracefully still takes several minutes, often > 15 min, and the index being is kept up with the blockchain, without having a huge amount of data to flush

**Comment by so7ow** [comment]
> Not indexing transactions doesn't make a visible difference

Did you reindex from scratch to change the indexing options? That's the only way the changes actually take effect.
