### ISSUE TITLE
Also return the runeID (block:tx) in on the output endpoints

### ISSUE THREAD

**Issue by pxr64** [ordinals/ord#3863]
Currently, the output endpoints only return the rune name and we need to make subsequent calls to return each rune ID.

**Comment by cryptoni9n** [comment]
> Currently, the output endpoints only return the rune name and we need to make subsequent calls to return each rune ID.

Hi @pxr64 - my feeling is that this is by design since the Rune ID isn't shown on the output page in `ord` ([example](http://ordinals.com/output/0718bffe106b878b593fbd41c1563ec96612d2cb1402bedd5e6241645575dcfd:1)) and therefore `ord` doesn't consider it to be info about the output that it should return.  If we want to add the Rune ID to the output page and the output endpoint, I think that would be fine.  However, I'm not sure if this was left off purposefully as being superfluous or cluttering to the other information about the output. @raphjaph what do you think?

**Comment by raphjaph** [comment]
I think we could probably add this to the JSON version of this endpoint.

**Comment by raphjaph** [comment]
Would something like this help? 
https://github.com/ordinals/ord/pull/3971

**Comment by raphjaph** [comment]
Haven't heard back so going to close this, please reopen or comment on the PR if you still need this.
