### ISSUE TITLE
Premine percentage not correct

### ISSUE THREAD

**Issue by mvdnbrk** [ordinals/ord#3985]
The premine percentage is not correctly calculated.

While a rune is still mintable, the premine percentage should be calculated by dividing the `premine` value by the maximum supply instead of the circulating supply.

https://github.com/ordinals/ord/blob/f1c1ee5adb39c54e99c79e65791b6339186c35be/templates/rune.html#L60

**Comment by cryptoni9n** [comment]
Hi mvdnbrk, this was a topic that was discussed quite a bit back in May.  Please refer to #3630 and especially #3748.  

First, the premine percentage is being calculated correctly - it is just confusing to many.  The premine percentage is based on the current circulating supply, not the maximum supply, and this is by design.

Previously, Casey has supported displaying the inclusion of the `mint progress` field and having the premine percentage for unmintable runes display as the premine percentage of the final supply - however, it occurs to me that this is already the case (ex: https://ordinals.com/rune/405). Since the premine percentage is the percentage of the current supply that was premined.  Once the rune goes unmintable, the current supply becomes cemented as final and the premine percentage is still the percentage of that supply.  

@casey what are your current thoughts about this?  These updates fell off of my radar but I'd be happy to continue on the path to improving the rune page.  Do you agree that the premine percentage will already display as the premine of the final supply once a rune is unmintable, or do I misunderstand?  If so, do we want to make any changes to emphasize that it is final or move on to the next change?

**Comment by casey** [comment]
I think the way it is is correct. The maximum supply is not guaranteed to be minted, so showing premine percentage as `premine/max_supply` is possibly underestimating the final premine percentage.

This does seem to be a common complaint though. @mvdnbrk why do you not like the way it's currently displayed?

**Comment by mvdnbrk** [comment]
I would say that someone who etches the rune has the intention to fully mint out.

When mint starts it would not show a realistic percentage of the premine.

Example:
100 max supply
10 premined

Premine percetage is 10% when fully minted.
Now it will show a 100% premine when no mints have taken place.

My suggestion would be to show a `live percentage` and `projected percentage` or something like that to make this more clear. And can eventually turn into something like we are having right now when mint is finished.
Which can be a full mint out or when a certain block height has been reached.

**Comment by SequoiaB** [comment]
100% agreed.
This would be a good solution.

**Comment by casey** [comment]
> I would say that someone who etches the rune has the intention to fully mint out.

It doesn't matter what their intention is, it only matters whether or not it actually mints out.

I'm honestly kind of unmoved by arguments that this should change.

What matters more to a potential minter, `premine / current supply` or `premine / max supply`? Definitely the latter.

Also, if your argument is that "someone who etches the rune has the intention to fully mint out", then if you expect the supply to eventually be the max supply, then we should display `premine / max supply`.
