### ISSUE TITLE
Standard Metadata Fields for Marketplace Scraping

### ISSUE THREAD

**Issue by elocremarc** [ordinals/ord#4049]
We need to create a suggested standardized metadata schema for collections to be scraped by marketplaces.
It doesnt matter if we have parernt child if we still need to upload metadata to marketplaces. 

This is pretty much standard operation on other chains like ETH.

I propose we use something like I did for blob. I setup blob with this standarizaton in mind.

```js
{
  "Name": "Blob #1",
  "attributes": {
    "Blob": "extreme",
    "Skin": "matrix",
    "Realm": "mental",
    "Blob Buddies": 1
  }
}
```
How it would look on ETH
```js
{
  "attributes": [
    {
      "trait_type": "Blob",
      "value": "extreme"
    },
    {
      "trait_type": "Skin",
      "value": "matrix"
    },
    {
      "trait_type": "Realm",
      "value": "mental"
    },
    {
      "trait_type": "Blob Buddies",
      "value": 1
    }
  ],
  "description": "....",
  "name": "Blob #1"
}
```
This is less than ideal for the attributes because "trait_type" and "value" will render on ordinals.com.  Therefore I combined them into a key value pair. Where the 'trait_type' is the key and the "value" is the trait name. 

If we all came to a consensus at least on a few SCHEMA structures like this it would make listing collections automatic

The other thing to consider having in this standard is showing if a parent has been burnt. This would be equivilent to a ETH dapp showing if a contract owner has been revoked. Then a buyer can know the collection is closed off when looking at the metadata on a marketplace.

**Comment by ep150de** [comment]
Like the concept, but I think marketplaces just need to bring in support displaying parent child based collections. Would they spend more resources scraping and tooling for a metadata standard? It might be asking for more than simply being a template or dashboard filter to show parent child collections might solve. Also requires all minting inscribing platforms to retool to some centralized standard rather than leaving it up to creators and permissionless model.And if searching for meta data, how do you know when you reached the end of a collection without a burn parent flag, simply sending to a satoshi wallet address isn't a signal platforms can easily scrape or search for without expensive apisAlso. How would the meta data be injected into existing collections that didn't have meta data because they didn't have the option or chose not to use it.Just curious constructive feedback as I too wish to have more coherence with collections and the DNA that defines them on chain.
-------- Original message --------From: Eloc ***@***.***> Date: 11/4/24  3:31 PM  (GMT-08:00) To: ordinals/ord ***@***.***> Cc: Subscribed ***@***.***> Subject: [ordinals/ord] Standard Metadata Fields for Marketplace Scraping
  (Issue #4049) 
We need to create a suggested standardized metadata schema for collections to be scraped by marketplaces.
It doesnt matter if we have parernt child if we still need to upload metadata to marketplaces.
This is pretty much standard operation on other chains like ETH.
I propose we use something like I did for blob. I setup blob with this standarizaton in mind.
{
  "Name": "Blob #1",
  "attributes": {
    "Blob": "extreme",
    "Skin": "matrix",
    "Realm": "mental",
    "Blob Buddies": 1
  }
}
How it would look on ETH
{
  "attributes": [
    {
      "trait_type": "Blob",
      "value": "extreme"
    },
    {
      "trait_type": "Skin",
      "value": "matrix"
    },
    {
      "trait_type": "Realm",
      "value": "mental"
    },
    {
      "trait_type": "Blob Buddies",
      "value": 1
    }
  ],
  "description": "....",
  "name": "Blob #1"
}
This is less than ideal for the attributes because "trait_type" and "value" will render on ordinals.com.  Therefore I combined them into a key value pair. Where the 'trait_type' is the key and the "value" is the trait name.
If we all came to a consensus at least on a few SCHEMA structures like this it would make listing collections automatic
The other thing to consider having in this standard is showing if a parent has been burnt. This would be equivilent to a ETH dapp showing if a contract owner has been revoked. Then a buyer can know the collection is closed off when looking at the metadata on a marketplace.

**Comment by casey** [comment]
I'm planning on first defining an on-chain metadata schema which can be converted to JSON, and that schema can also be used to upload/download metadata from marketplaces. So I think this should wait until that schema is defined, but I'll keep it in mind while I'm working on it.
