### ISSUE TITLE
Collections and Provenance

### ISSUE THREAD

**Issue by casey** [ordinals/ord#783]
See this comment for an update: https://github.com/casey/ord/issues/783#issuecomment-1495169403

Provenance is important for art, and a large part of how it derives its value. We should have some notion of the provenance of an inscription:

- For an inscription, see who made it
- For a creator, see which inscriptions they've made
- Allow referencing an inscription within an artist's body of work by number or name (maybe just name, so they aren't confused with symbols) `/ARTIST_SYMBOL/NUMBER`

This will likely be accomplished as follows:

- If the inscription reveal transaction contains more than one input, the first ordinal of the first input is the "prime" ordinal
- If inscription has a prime ordinal, the first output of the inscription is ignored for the purposes of figuring out which ordinals are inscribed
- If an inscription has a prime ordinal, the inscription page should link to the prime ordinal's page
- If an ordinal has been used as a prime ordinal, the ordinal page should list all inscriptions it's made

It should be possible to make a series of related inscriptions:

- If an inscription is part of a collection, it should link to the collection page
- The collection page should link to all inscriptions in the collection
- The collection page should have some description about the collection
- It should be possible to nest collections. E.g. create a collection that contains multiple collections.
- Collections should have provenance. You should be able to see the scribe who created a collection, and see the collections issued by a scribe.
- It should be possible to make a collection closed-ended, e.g. guarantee that it isn't possible to issue more items.
- It should be possible link to an item in a collection by number or possibly name, e.g. - `/COLLECTION_SYMBOL/NUMBER` or `/COLLECTION_SYMBOL/NAME`.

Design sketch:

- Reuse prime ordinals from #783. A collection is just a prime ordinal, and all the inscriptions that it's made. 
- If you want to add a description to the collection, make an inscription on the prime ordinal used to issue the collection.
- If you want to close the collection, send the prime ordinal to an OP_RETURN. (I don't actually like this. It seems bad to force burning the prime ordinal of a collection. But, it's very simple.)

**Comment by rot13maxi** [comment]
this sounds awesome

**Comment by dannydeezy** [comment]
i'm a bit confused by this line
> If inscription has a prime ordinal, the first output of the inscription is ignored for the purposes of figuring out which ordinals are inscribed

let me see if i get this right:
Say I want to make a collection Astral Babes with good provenance. 
So I create an inscription w/ info about the collection like normal onto the first satoshi of Outpoint-A, which a value of 10,000 sats

Now say I want to mint the first Astral Babe, the transaction will look like this
Inputs:
- Outpoint-A (10,000 sats)
- Some other utxo w/ reveal script encoding the first Astral Babe JPG data
Outputs:
- Outpoint-B (10,000 sats)
- Outpoint-C (any amount)

Now Astral Babe 1 lives at the first satoshi of Outpoint-C
And we can infer that she is part of the Astral Babes Collection, which lives at the first satoshi of Outpoint-B

As I understand, this is a breaking change, because with existing rules, the above transaction would inscribe Astral Babe 1 onto the first sat of Outpoint-B

I'm not sure I like this because it's a breaking change

I will think of something to propose instead

**Comment by dannydeezy** [comment]
> This is non-breaking. We'll add a field, `destination`, which is an integer. `destination` is an even field, so clients that don't understand it will ignore inscriptions with that field. When an inscription has a `destination`, it is made on that sat in the output. This can be used to add features which change the existing rules for individual inscriptions.
> 
> The `destination` field can also be used for other features, for example, multiple inscriptions per transaction.

awesome

**Comment by dannydeezy** [comment]
i wonder if there's a way we can retroactively add items to a collection
somehow construct a transaction whos inputs include the ordinal of the collection and the ordinal of the item, as well as an inscription on the collection ordinal that brings the item into the collection

just thinking of ways i can launch my items asap and retroactively add them to a collection

**Comment by haribosan** [comment]
Retroactive collections seem doable. One issue I can think of is that early inscriptions will be sought after for the purposes of giving new collections some kind of antiquity. This is a market thing though, so probably no biggie.
Mostly this could be a clever solution to #1189: if I buy an inscription, I can add it to my own collection as in set of collected items, by linking it to my collector's (as opposed to creator's) prime ordinal.

**Comment by dannydeezy** [comment]
Until the above can be released, I'm thinking of using Nostr messages for provenance, something like this:

Create Astral Babes Nostr key
Create an publish a Nostr message from the above key announcing the collection in JSON format, something like:
```
{
"name": "Astral Babes",
"maxSupply": 10000
}
```
Create and mint a text inscription of the above Nostr message


Each time a mint occurs, the Astral Babes Nostr account publishes a Nostr message to attest that this item is part of the collection
{
 "inscription_id": "asdfasdfasdfasdfasdf"
}
And this message gets minted as its own inscription, we'll call it an "Attestation Inscription" (it is a separate from the actual JPG image inscription)


The valid 10,000 items in the collection are the first inscriptions to be mined and also have a valid attestation inscription mined after it.

Furthermore, additional Attestation Inscriptions can be minted afterwards to add things like traits, names, etc to an existing JPG inscription. Also can mint a "Freeze Metadata" Attestation which can freeze all future updates to an item or an entire collection


I think the key here is to decouple the inscription types from each other to allow for more flexibility

**Comment by haribosan** [comment]
A distinction between creator's prime ordinal and collector's prime ordinal would be chronological: the first prime ordinal inscription would be the creator's; the latest, the latest collector's.

**Comment by dannydeezy** [comment]
> @dannydeezy
> 
> > Until the above can be released, I'm thinking of using Nostr identities for provenance, something like this:
> 
> It looks like all the actually metadata in this scheme is in inscriptions, and the only nostr-y bit is the pubkey of the creator, is that right?

yeah correct

**Comment by dannydeezy** [comment]
could also link items to a collection in batches like this, to reduce dust
these can get minted to an OP_RETURN output as there's not need to send them anywhere after being inscribed.
(they could even be just published as OP_RETURN data in the first place...)
```
{
 "collection_id": "inscription-id-of-the-collection-announcement-inscription",
  "items":[{
         "inscription_id": "asdfasfasdf"
         "name": "Astral Babe 1",
         "traits": ["hot"]
      }, {
          "inscription_id": "ccasdfasfasdf"
         "name": "Astral Babe 2",
         "traits": ["sexy"]         
      }, {
         "inscription_id": "ffffaaaasdddsd"
         "name": "Astral Babe 3",
         "traits": ["inquisitive"]
      }
  ],
 "signature": "signed-by-the-nostr-key-of-collection-owner"
}
```

**Comment by dannydeezy** [comment]
actually yeah, there's no reason collection or metadata announcements need to be inscriptions, because they aren't "owned" or "transferrable", so the initial announcement:
```
{
"name": "Astral Babes",
"maxSupply": 10000,
"owner": npub12344(nostr-pub of owner)
}
```
and messages that link items to the collection:
```
{
 "inscription_id": "inscription-id-of-the-jpg-inscription",
 "collection_id": "inscription-id-of-the-collection-announcement-inscription",
  "name": "Astral Babe 12",
  "traits": ["hot", "sexy"],
 "signature": "signed-by-the-nostr-key-of-collection-owner"
}
```

could just be encoded as OP_RETURNs...

**Comment by dannydeezy** [comment]
ah but the issue is OP_RETURNs have a byte limit, I see.
In that case, perhaps they should be inscriptions

**Comment by casey** [comment]
Could you open a discussion or something for this? It's totally reasonable to discuss, but I don't want people to think it's recommended/supported/under consideration as the official way of doing this.

**Comment by dannydeezy** [comment]
> Could you open a discussion or something for this? It's totally reasonable to discuss, but I don't want people to think it's recommended/supported/under consideration as the official way of doing this. Just hid the comments, just want to keep this issue focused on the planned implementation for ord.

if `ord` is definitely going to go this route, then I would request that we consider some way in which a bunch of items launched today before this feature is released could have a path to becoming compliant with the standard that does get decided on

**Comment by rot13maxi** [comment]
started discussion here: https://github.com/casey/ord/discussions/1460

**Comment by casey** [comment]
If you figure out another way to do provenance, e.g. a master inscription with the txids, or nostr, etc, then you can publish that on the project page such that that users can verify it. I can't promise specific support for anything in `ord` though.

**Comment by dannydeezy** [comment]
> Reuse prime ordinals from https://github.com/casey/ord/issues/783. A collection is just a prime ordinal, and all the inscriptions that it's made.

Is this linking the correct issue? it's just linking back to this one

**Comment by casey** [comment]
@dannydeezy Yup, that links to this issue.

**Comment by dannydeezy** [comment]
Curious for thoughts on this - a way to almost do what's mentioned here but without requiring the collection ordinal to be present on every mint transaction: https://github.com/casey/ord/discussions/1469

**Comment by casey** [comment]
> Mempools do not accept a chain of more than ~30 unconfirmed transactions, so that means only 30 items can be minted per block. This hinders the ultimate degen experience of a full 10,000 item collection getting minted out in minutes

Multiple inscriptions per transaction, tracked in #876, fixes this. Can RBF one mint transaction to include more and more inscriptions, until eventually you mine a single four megger that includes all inscriptions and only needs to move the parent ordinal once.

**Comment by rayonx** [comment]
Alternative scheme if BIP-322 can be used for message signing to prove collection, by explicitly signing using the aggregate signatures from all other inscriptions' genesis addresses. This is useful if they don't come from the same prime ordinal, but you want them as a collection post-inscribing because you have the keys to each genesis addresses.

Message to sign by all addresses within the collection:
| Data row              | Type             | Description                                                                                                                                                                                        |
|-----------------------|------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Nonce (uint64)        | Required         | Default value of 0 if unused. Nonce can be used by marketplaces or individuals to attest ownership of collection.                                     |
| Inscriptions ID  | Required         |              inscription_id of all the inscriptions in the collection, on every subsequent newline. All the genesis addresses listed here must sign this message                                                                                                                               |

**Comment by casey** [comment]
blaeeeeeeeeeghtghghghg:

```rust
parent: inscription.parent.and_then(|parent| if inscriptions.contains(parent.txid) { Some(parent) } else { None }),
```

**Comment by veryordinally** [comment]
Provenance is important for art, and is a large part of how it derives value. More broadly, establishing a standard for on-chain provenance using Bitcoin’s proven foundation enables provenance for any sort of digital artifacts.

We should have some notion of provenance for inscriptions that satisfies these requirements:

1. For an inscription, see who made it
2. For a creator, see which inscriptions they've made
3. Allow referencing an inscription within an artist's body of work by number or name (maybe just name, so they aren't confused with symbols) `/ARTIST_SYMBOL/NUMBER`

This will be accomplished as follows:
- We are introducing the concept of parent-child relationships between inscriptions
- When an inscription is created, it can be made the child of an existing inscription, which becomes its parent
- The UTXO that currently holds the parent inscription is an additional input to the reveal transaction for the child inscription and spent to a separate output in the reveal transaction
- The parent relationship needs to be established when an inscription is created and *cannot* be added or changed later
- An inscription can only have one (or no) parent
- If an inscription has a parent, the child's inscription page will link to the parent's inscription page in the ordinals explorer
- If an inscription has been used as a parent inscription, the parent's inscription will contain links to all of its child inscriptions in the ordinals explorer

This concept can be used for provenance (with the parent inscription representing an artist), and it can also be used to establish collections:

- If an inscription is part of a collection, all inscriptions that are part of the collection should have a single parent inscription representing the collection as their parent.
- The collection inscription could in turn have the inscription representing the artist as its parent. 
- Additional levels can also easily be established, for example to establish groups of collections, or sets in a collection.
- Collections can be made closed-ended by burning the collection inscription.

**Comment by dsv9** [comment]
Taking in consideration this specification:

> The parent relationship needs to be established when an inscription is created and cannot be added or changed later

we cannot assign parents to currently inscribed items, right?

**Comment by loon3** [comment]
so what prevents someone from creating a collection from a parent inscription they bought/acquired?  seems like a great way for scammers to create "official" collections from someone else's inscription

**Comment by dsv9** [comment]
@loon3 I believe this specification is what would prevent your scenario, since the parent-child relationship can be established only at the moment of the inscribing, and cannot be changed afterwards.

> The parent relationship needs to be established when an inscription is created and cannot be added or changed later

**Comment by loon3** [comment]
yes for the child, but the parent is simply an inscription you already hold (if i read that right)

**Comment by WinkyDev** [comment]
Let's determine the problem first,
We need to know which inscription belongs to which collection or an artist.
There are multiple methods suggested in this thread to make this happen, but there are some problems that occur over and over.
Provenance needs to be structured very carefully to avoid problems in the future, that's a big deal.
**Parent inscription** - from what I understand, you can't forecast the inscription id of the child, so the parent must be created after we create the child. That can work but limits functionalities like dynamic allocation of pieces in the collection, and if you want to allow your community to inscribe the NFTs (to avoid paying all the gas fees), they need to trust you to wrap it all with a "parent inscription" that will state that they are within the collection. 
To fix that issue you may suggest inscribing a parent for each inscription with its collection, but that will require you to add signing to create a relationship between the parents in a way that is much simpler to implement without the need for parents at all (the second method of using signature)

**Signatures** - The convo here about "where" to place the signature is pretty much irrelevant, as there are multiple ways to add metadata (natively into the files -exif and such, multipart content type, another inscription which indicates).  The real focus is on how and what we should sign. a general message from the author's wallet is vulnerable because an attacker can take this signature and attach it to another inscription which will make it "official".

### There are two solutions that can work:
1. **Pre-inscribing:**  Adding metadata of "token_id","collection_name", "author wallet", and "unique_signature" into the inscription. and the unique signature will be based on https://en.bitcoin.it/wiki/Message_signing which can be validated later on, and will contain the "token_id" + "collection_name" + "author wallet". That way the signed message is not general as it is represented by each "token_id" which is unique for every inscription in the collection. This can be generated upfront and added to the file natively before the inscribing even begins. [Big advantage here is that we can leverage the web3.js infra which is widely adopted already to create signatures from other protocols]

2. **Post-Inscribing:** Creating a new inscription with the metadata that is meant to be the parent. It will include the data of: "inscription id","collection_name", "author wallet", and "unique_signature". The unique signature will contain "inscription id"+"collection_name",+"author wallet". That way we can validate that this inscription really created by the wallet of the author we want. (we can also create metadata-inscription (parent) for multiple child inscriptions, with 1 signature that can be more efficient in fees)

FYI: We have created a tool to add metadata into jpegs https://digital-artifacts.io already which you can test for that purpose. it is currently biased toward solution number 1 (pre-inscribing) but will be changed as to what the project will decide.
<img width="1049" alt="Screen Shot 2023-03-04 at 21 52 56" src="https://user-images.githubusercontent.com/69144568/222926059-74abc23d-c3c6-4ae8-8fd1-51a2ac7b336a.png">

**Comment by rot13maxi** [comment]
One tradeoff with the “have the parent be an input to the reveal tx” method of linkage is that collections will have to be inscribed serially (at least in terms of the transaction graph, in practice, CPFP would let you have ~20 of them in the mempool at a time”. Common practice for medium to large collections now is to try to bulk inscribe in parallel. Artifacers will have more complex transaction management for larger collections. 

Then again, maybe thats desirable in and of itself. A large collection with common inscription input would itself be a feat until better tooling is developed.

**Comment by ericatallah** [comment]
To support generative art collections, in which the art is all contained in the parent inscription, does it make sense to create a JSON schema standard for child ordinals to define their relationship to a parent?

For example, a parent ordinal renders a single item in it's collection based on a url param, `?tokenID=4969` for example.  So each child ordinal of this collection is just a JSON doc following some standard:

```
{
   "collectionId": "<inscription id of parent>",  // (probably unnecessary)
   "id": 4969,
   "urlParams": ["tokenID=4969"],
   "mimeType": "text/html"
}
```

Whenever ordinals explorer parses child inscription data which is a JSON doc, it displays a `metadata` section on the inscription page, and renders that particular item in the collection using the same rules for MIME types it already has.  So in the example above, it would render an `iframe`, something like:

```
<iframe src="/content/<inscription id of parent>?tokenID=4969" />
```

**Comment by skyrover7** [comment]
> if `ord` is definitely going to go this route, then I would request that we consider some way in which a bunch of items launched today before this feature is released could have a path to becoming compliant with the standard that does get decided on

@veryordinally appreciate all of the context provided! curious whether the above comment was taken into consideration or how existing inscription collections can incorporate this? if at all?

**Comment by 0xKalakaua** [comment]
> Provenance is important for art, and is a large part of how it derives value. More broadly, establishing a standard for on-chain provenance using Bitcoin’s proven foundation enables provenance for any sort of digital artifacts.
> 
> We should have some notion of provenance for inscriptions that satisfies these requirements:
> 
> 1. For an inscription, see who made it
> 2. For a creator, see which inscriptions they've made
> 3. Allow referencing an inscription within an artist's body of work by number or name `/PARENT_INSCRIPTION/NUMBER`
> 
> This will be accomplished as follows:
> 
> * We are introducing the concept of parent-child relationships between inscriptions
> * When an inscription is created, it can be made the child of an existing inscription, which becomes its parent
> * The UTXO that currently holds the parent inscription is an additional input to the reveal transaction for the child inscription and spent to a separate output in the reveal transaction
> * The parent relationship needs to be established when an inscription is created and _cannot_ be added or changed later
> * An inscription can only have one (or no) parent
> * If an inscription has a parent, the child's inscription page will link to the parent's inscription page in the ordinals explorer
> * If an inscription has been used as a parent inscription, the parent's inscription will contain links to all of its child inscriptions in the ordinals explorer
> 
> This concept can be used for provenance (with the parent inscription representing an artist), and it can also be used to establish collections:
> 
> * If an inscription is part of a collection, all inscriptions that are part of the collection should have a single parent inscription representing the collection as their parent.
> * The collection inscription could in turn have the inscription representing the artist as its parent.
> * Additional levels can also easily be established, for example to establish groups of collections, or sets in a collection.
> * Collections can be made closed-ended by burning the collection inscription.

This is amazing. Is there an ETA on this? I've been holding on releasing a project waiting for this. Also if there is a way of beta testing this I want to be a part of it if possible. Thank you!

**Comment by tyjvazum** [comment]
> > * Collections can be made closed-ended by burning the collection inscription.
> 
> Meaning burn the coins? I don't think burning bitcoins should be encouraged (or forced even if you want to have a legit/valid closed-ended collction).
> 
> Instead, given parentage is defined by the parent being an input to each reveal transaction, the final inscription in a collection could be signalled by 'closing the loop' with the parent, and the output sending it back to the address of the first inscription (its own genesis). Address re-use feels much better than destroying Bitcoins?
> 
> (also assuming I've understood the proposal and how `ord` works sweat_smile)

Yes, it means burning the sat.

I agree with you that there are various ways to avoid burning sats.

However, Casey has expressed strong interest in burning sats as a means of implementing features: https://github.com/casey/ord/issues/784, https://github.com/casey/ord/issues/1333, https://github.com/casey/ord/issues/1501, https://github.com/casey/ord/issues/1548, https://github.com/casey/ord/issues/1588, https://github.com/casey/ord/issues/1657

**Comment by lowkeycoders** [comment]
Mind checking the solution I have proposed?
https://mirror.xyz/0xa39f4896604D861521587F735241237cF803d90E/vwuiIJNaNYR6yQ3JiV9tdpeCEEsgKaWo8WytWYhRzeA

It enables parent child relationship and in the end collection owner can do final inscription which will be a json and inscription id will act like 'smart contract' address of ETH. 
It prevents all sort of scam usecases during collection mint or after mint.

**Comment by stet** [comment]
For provenance purposes, an inscription representing an artist/creator/publisher etc and used as a parent inscription should NOT be associated with an ordinal sat and should NOT be movable/tradable. The functionality for creating a parent inscription used as an owner identity should be worked out first. 

There is work and discussion on arbitrary protocol specifiers in a forked Ord repo to handle generic non-ordinal inscription use cases. I have also proposed the notion of namespaces to define different conventions and standards around inscriptions and whether or not they are attached to ordinal satoshis. 

Unless a good argument can be made for enabling the movability of a parent inscription used as an owner and source identifier, I think this should be a focus now before deploying provenance parent-child support. 

In some cases, such as a desire to move your identity "token" to a different address/wallet, it could make sense to ordinalize it. However, there are surely other ways to handle this that can be discussed. Ultimately, I see no reason why, once inscribed, an ID should move via an ordinal sat. 

Also, I think a standard metadata format should be created for an owner/artist ID inscription that is intended to have a body of work associated through children inscriptions.

**Comment by checkthecodes** [comment]
> Mind checking the solution I have proposed? https://mirror.xyz/0xa39f4896604D861521587F735241237cF803d90E/vwuiIJNaNYR6yQ3JiV9tdpeCEEsgKaWo8WytWYhRzeA
> 
> It enables parent child relationship and in the end collection owner can do final inscription which will be a json and inscription id will act like 'smart contract' address of ETH. It prevents all sort of scam usecases during collection mint or after mint.

I read through it and seems promising. Key things I like about this approach:

1. Parallel inscriptions of multiple items as no prime ordinal required in the input
2. Unique identification of every item in a collection through parent-child and child-parent relationships
3. Support for metadata/traits
4. Backward compatibility with existing explorers
5. Easy to inscribe without any learning curve for existing creators/users
Excited to see how it progresses.

**Comment by satoshi0770** [comment]
> so what prevents someone from creating a collection from a parent inscription they bought/acquired? seems like a great way for scammers to create "official" collections from someone else's inscription

dont see this as an issue but instead a feature.
if someone buys an inscription, they can later use it as a parent for later inscriptions.
this can possibly create interesting demand for certain inscriptions
ex: artist or collection buys a sub 1k inscription to use as their "parent" for future collections
ex: artist or collection buys a specific inscription from a collection to use as their "parent" for future collections
essentially we are adding utility to every inscription, since the added utility is it can be used as a parent for future inscriptions!
this is a great feature add for ord

**Comment by tyjvazum** [comment]
Is it possible for any project collaborators to comment on or otherwise address any of the discussion here over the past week?

**Comment by null-prophet** [comment]
This all sounds very promising step forward.

More generally then, will there be some standards for the JSON structuring of parent/child collection/ordinal inside collection done?

I'm looking at making a project that would allow the images to be mutated/modified as time went by so wouldn't want them on chain but the collection would have a root JSON file showing collection info and the child ordinals would have the JSON specific to them, I had initially though using the enjinn/opensea style metadata format would be best as it seems to handle most eventualities regarding data and links and there is a lot of prior art out there using this JSON structure to display or catalogue collections, which makes it easier for wider adoption of ordinals.

**Comment by dajuguan** [comment]
Even though we can prove an inscription belongs to one collection, but the provenance of collection itself has to be done by off-chain identity, because there is no way we can distinguish different transactions with the same meta-data. We have to identify the creator's address by off-chain.

**Comment by AngusP** [comment]
> We have to identify the creator's address by off-chain.

SO.... you could inscribe a PGP Public Key, then using sats from the output of that transaction (change) inscribe everything in the collection, then finally create another text file inscription using the PGP key to sign a message that says something like

```
101 Monkey JPEGs

A limited collection of 101 inscriptions by <Creator's ID>

<inscription ID>
<inscription ID>
...
<inscription ID>

-----BEGIN PGP SIGNATURE-----

a5Dfa5Dfa5Df...
...
a5Df
-----END PGP SIGNATURE-----
```

So-long-as the initial pubkey has enough sats in it that you can include some in every inscription in the collection, this works with doing concurrent inscriptions (i.e. doesn't require 'chaining' the transactions) and also uses PGP which is an existing and widely used way of having a digital identity, and does all this on-chain rather than requiring off-chain (out of band) verification.

You culd make it a bit more complex by a creator having a permanent PGP key, and making an ephemeral one for the collection, sign it with their permanent key, sign the collection text file with the collection key, and include the revocation certificate for the collection key in the collection text file too to 'invalidate' using the collection key again to make any new inscriptions

**Comment by null-prophet** [comment]
would using an ECDSA signed hash/message not be more size efficient and more in keeping with things that are widely used in the crypto space?

The public key could be in the root of the collection ordinal and using a function you could validate the signature in each child has been made with that key.

**Comment by AngusP** [comment]
> would using an ECDSA signed hash/message not be more size efficient

Yeah sure, it would be smaller, though PGP is 'handy' in that it is already (fairly) widely used and understood (even if the UX often sucks 😆) and makes it easy to attach names, emails and photos to an ID, and has the potentially useful concepts of revocation certificates and keys signing eachother to indicate authenticity/trust.

**Comment by null-prophet** [comment]
I know, but it sounds like thats overengineering what amounts to a mini blockchain inside an ordinal to prove some kind of parent child linkage/proof.

**Comment by tyjvazum** [comment]
A major issue with using GPG/PGP is that it would be separate key material, which would need to be persisted somehow, and would likely cause a lot of confusion for users tasked with storing added backup data beyond the seed phrase for the wallet.

**Comment by veryordinally** [comment]
Continuing work in #1963

**Comment by clean-casey** [comment]
I am trying to understand the improved security of this approach. My use case is to publish a document and mint a collection of child inscriptions that all reference this document. Can someone describe the benefits of this provenance parent/child feature versus just referencing the parent inscription in the child inscriptions. Thanks

**Comment by clean-casey** [comment]
> 

Thank you @tyjvazum for the additional context. This is very helpful. I am happy to help if I can. Thank you @casey

**Comment by rot13maxi** [comment]
I think this approach is problematic for collections over a handful in size. The current state of the art is to inscribe a collection in parallel. Requiring a “collection parent” sat to be shuffled into the reveal tx of each item in the collection greatly limits your options for inscribing a collection: you can either do them all sequentially or if you’re very clever with CPFPing the parent around, you might be able to have small batches of 25 in the mempool at a time. The latter approach hasnt been developed (afaik) and may carry some risks and will come with high fees to keep all of those linked transactions in the same block — because you have to cpfp the parent ordinal around, all the the reveal transactions are going to be linked together onchain and move around the mempool as a batch with all of their transaction fees averaged together. 

I know people are excited for *something* to let them do collections in a standardized way, but I dont think everyone understands the current proposal and the implications it will have on the ability to actually inscribe collections. 

The inscription envelope has room for headers. I think a more scalable approach would be something like an ord header that references a “parent” inscription and contains a signature (bip322 or otherwise) that proves possession of the parent inscription at the time the child was inscribed. That kind of approach fits better with the current economic and operational needs of artifacers working today.

**Comment by bodily11** [comment]
I agree with @rot13maxi. We're looking to inscribe 10k generative collections using better collection standards and provenance information, but requiring a parent inscription in this fashion is unworkable for us. I would definitely prefer some kind of bip322 parent inscription owner signature standard.

**Comment by rot13maxi** [comment]
Alternative ideas that could be formalized a little more and help with the scalability issue (borrowing some ideas from the Taproot Wizards project):
- inscriptions with a address/scriptpubkey as a common ancestor are part of a collection. Maybe there's a special inscription that can be made using that SPK to set collection metadata
- inscriptions all sent to the same address/scriptpubkey (using the `--destination` flag on `ord wallet inscribe`) are part of the same collection. Again, maybe there's a special "marker" inscription that could be made to set inscription metadata.

**Comment by timechainz** [comment]
I agree with @satoshi0770 about the glorious opulence of the prime ordinal technique.  

I'd like to throw an additional idea out there that could address the scaling issues @rot13maxi raises.

An inscription's reveal transaction may include additional outputs.  The first sat in each output may be used to inscribe a child.  Using this technique an inscription would be made with a pre-determined number of potential children. 

Outputs

0:  10,000 sats - collection anchor
1:  330 sats - potential child 1
2:  330 sats - potential child 2
…

Advantages to this system are that the number of potential children are known up front and it scales very well.  One could immediately send all children to the mempool after confirmation of the parent.  Downside is that the index would probably have to track the potential child satpoints.

**Comment by casey** [comment]
Sorry for the delay in getting this feature done! `ord` is an open source project developed by volunteers, as well as a limited number of paid contributors. Like many open source projects, we have limited bandwidth, and often are dealing with many concerns at the same time. Collections is an important feature, but there are other important things to be done, including fixing bugs and improving the UX of existing features.

Collections is also complicated, and will require careful review and revision. I'm personally optimistic about the state of the design of collections and its implementation. However, it would not be personally acceptable to me to release a feature that was buggy, half-baked, or insecure. As they say: Collections will be done when it's ready, and not a moment sooner.

Enjoy the current features of ord! Development continues :)

**Comment by sherbakovdev** [comment]
Here is the proposal for the collection protocol. I wasn't aware of the discussion here, so we have found another solution to this problem with my team: https://brc721.com

**Comment by p0stcapone** [comment]
> I think this approach is problematic for collections over a handful in size. The current state of the art is to inscribe a collection in parallel. Requiring a “collection parent” sat to be shuffled into the reveal tx of each item in the collection greatly limits your options for inscribing a collection: you can either do them all sequentially or if you’re very clever with CPFPing the parent around, you might be able to have small batches of 25 in the mempool at a time. The latter approach hasnt been developed (afaik) and may carry some risks and will come with high fees to keep all of those linked transactions in the same block — because you have to cpfp the parent ordinal around, all the the reveal transactions are going to be linked together onchain and move around the mempool as a batch with all of their transaction fees averaged together.
> 
> I know people are excited for _something_ to let them do collections in a standardized way, but I dont think everyone understands the current proposal and the implications it will have on the ability to actually inscribe collections.
> 
> The inscription envelope has room for headers. I think a more scalable approach would be something like an ord header that references a “parent” inscription and contains a signature (bip322 or otherwise) that proves possession of the parent inscription at the time the child was inscribed. That kind of approach fits better with the current economic and operational needs of artifacers working today.

I think that we're over complicating provenance in a number of ways.

Provenance was possible with the first release of ord which supported mainnet:  A single UTXO funds many UTXOs which immediately become inscriptions.

For many collections, if you look at the second ancestor of the genesis transaction, you will find one transaction which creates many ouptuts (because this was the simplest and most direct way to set up the funding for each individual inscription).  This transaction represents a strong (although slightly imperfect) record of provenance.  If this transaction were to create many UTXOs which went to the same address, it would be a perfect record of provenance.

If the initial funding UTXO contained an inscription (perhaps by mandate located at sat Index 0), then it would be very clear that this was the "parent" inscription.

There would be no changes necessary to ord to accomplish this, and there would be many collections who would be adopted by default into the provenance standard if this were adopted.

**Comment by rot13maxi** [comment]
I like this approach of having common ancestor ScriptPubKeys (some links to examples provided in this comment: https://github.com/casey/ord/issues/783#issuecomment-1492070385)

I think most of the work would be on indexing to add links between related items. On the inscribing side, it can either be handled with external tooling, or if we wanted to have `wallet inscribe` be able to either do bulk inscriptions or just to add an inscription to an existing collection, it would involve shuffling around some sats to the parent address and then inscribing.

**Comment by timechainz** [comment]
> There would be no changes necessary to ord to accomplish this, and there would be many collections who would be adopted by default into the provenance standard if this were adopted.

@p0stcapone In general I like the approach of having a common ancestor define a collection, but would adjust slightly to make fewer assumptions how collections are inscribed and funded.  A few things I would clarify:

* "A single UTXO funds many..."  - There should be a single tx, not necessarily a single utxo.  This is especially true if the genesis tx were to include a parent inscription.  
* The language is focused on the "funding" but it should be on the satpoint that is ultimately inscribed.  If other utxos are used for fees or padding during inscription it's irrelevant.  There are situations such as inscribing on special sats where it may not make sense to graft in the funding sats into the genesis tx.   I think this is effectively what you meant anyway.
* "...create many UTXOs which went to the same address..." - The intermediate address that holds the utxos that will be inscribed on is not really important and some wallets won't even allow sending multiple utxos to the same address (e.g. bitcoin-cli).  @rot13maxi 's 2nd alternative "inscriptions all sent to the same address/scriptpubkey" seems like a better way to enforce this.  

My $.02

**Comment by veryordinally** [comment]
Next step is implementing #2045

**Comment by casey** [comment]
I opened a [draft PR](https://github.com/ordinals/ord/pull/2278) with a spec. Comments welcome!

Please note that this spec does not include:

1. Batching, which would allow making multiple inscriptions in a single transaction.
2. A tag which makes an inscription not land on the first sat of the first output.

Which makes provenance more useful.

These can be specced and implemented separately, so they aren't included in the initial spec.

**Comment by casey** [comment]
This is finally done!
