### ISSUE TITLE
Recover from partial inscription using recovery key

### ISSUE THREAD

**Issue by casey** [ordinals/ord#904]
If the reveal transaction is not or cannot be mined, we should allow recovering inputs to the reveal transaction using the saved recovery key.

**Comment by hashbender** [comment]
Would offer a bounty on this one 👍

**Comment by dannydeezy** [comment]
are we screwed if we tried inscribing with `--no-backup` here and it got stuck before making the reveal? @raphjaph @casey

**Comment by dannydeezy** [comment]
the [acidelectro](https://ordinals.com/sat/acidelectro) satoshi card might be stuck in a commit tx forever 😂😂

**Comment by raphjaph** [comment]
If you did with `--no-backup` you literally do not have the key to recover it, so yea you're screwed. Otherwise Bitcoin Core seems to recognize the unspent commit output and you can use it normally after it has been mined

**Comment by dannydeezy** [comment]
> If you did with `--no-backup` you literally do not have the key to recover it, so yea you're screwed. Otherwise Bitcoin Core seems to recognize the unspent commit output and you can use it normally after it has been mined

is there a reason for using a random key pair here instead of deriving a key from the wallet's seed?

**Comment by raphjaph** [comment]
That's a good point. I always thought we take a key from the wallet but just checked and we generate a new one.

The reason we need to back it up (I think) is because it is a `rawtr` descriptor (a tap-tweaked script). Now if we take a key from the wallet would that be enough for Bitcoin Core to find this weird output without the accompanying descriptor? 

If you want to do some testing around this and open a PR I'd be happy to help!

**Comment by raphjaph** [comment]
We do recover from this
